name: ULSE
type: retriever

encoder:
  _target_: source.encoder.EmbeddingEncoder.EmbeddingEncoder
  vocab_size: ${data.vocab_size}
  embedding_dim: 768
  rpr_dim: ${model.rpr_dim}

rpr_dim: 128
vocab_size: ${data.vocab_size}

lr: 1e-3
base_lr: 1e-4
max_lr: 1e-2
weight_decay: 1e-2


