name: ULSE
type: retriever

encoder:
  _target_: source.encoder.EmbeddingEncoder.EmbeddingEncoder
  vocabulary_size: ${data.vocabulary_size}
  embedding_dim: 768
  rpr_dim: ${model.rpr_dim}

rpr_dim: 128
vocabulary_size: ${data.vocabulary_size}

lr: 1e-2
base_lr: 1e-3
max_lr: 1e-1
weight_decay: 1e-2


