name: XRR

type: reranker

encoder:
  _target_: source.encoder.BERTEncoder.BERTEncoder
  architecture: bert-base-uncased
  pooling:
    _target_: source.pooling.HiddenStateAveragePooling.HiddenStateAveragePooling

num_labels: ${data.num_labels}

embedding_dim: ${model.hidden_size}
man:
  _target_: source.man.MutualAttention.MutualAttention

hidden_size: 768
num_classes: 2

dropout: 0.1
dropout_1: 0.1
dropout_2: 0.4

tokenizer:
  architecture: ${model.encoder.architecture}


lr: 5e-5
base_lr: 1e-6
max_lr: 1e-4
weight_decay: 1e-2

